# Generated by Django 5.2.3 on 2025-07-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_taskcategory_task_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskcategory',
            name='system_defined',
            field=models.BooleanField(default=False),
        ),
    ]
